[package]
name = "phrustpam"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
dirs = "5.0.1"
reqwest = { version = "0.12.5", features = ["blocking", "cookies"] }
rpassword = "7.3.1"
